# Funding links displayed on the repository
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Reinasboo]
# ko_fi: # Uncomment and add username if applicable
# custom: ["https://your-funding-page.com"]
